sudo: required

services:
  - docker

language: r
cache: packages

before_install:
  - "docker pull ubuntu:16.04"
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install libgdal-dev libgeos-dev libproj-dev libudunits2-dev libv8-dev libprotobuf-dev protobuf-compiler libjq-dev

r_packages:
  - sp
  - rgdal
  - rgeos

warnings_are_errors: false

#Define R-versions
r:
  - release
  - devel

# apt_packages:
#   - libv8-dev
#   - librsvg2-dev

r_github_packages: 
  - r-lib/testthat
  - r-lib/covr

# environment variables set for all builds
env:
  global:
  # don't treat missing suggested packages as error
  - _R_CHECK_FORCE_SUGGESTS_=false

# before_script:
#   - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then R -e "install.packages('rgdal', type = 'source')"; fi

after_success:
  - travis_wait 40 Rscript -e 'covr::codecov()'

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - devscripts 
      - libudunits2-dev
      # - libproj-dev
      # - libgeos-dev
      # - libgdal-dev
      - libgtk2.0-dev

