language: r
r:
  - release
  - devel
  - oldrel

repos:
  CRAN: https://cran.rstudio.com
  
warnings_are_errors: false

deploy.skip_cleanup: true

os:
  - linux

sudo: true
dist: bionic

cache:
  - packages

before_install:
    - sudo apt-get install -y udunits-bin libproj-dev libgdal-dev libgeos-dev libudunits2-dev gdal-bin
    - R -e 'install.packages("rgdal", repos=c("http://R-Forge.R-project.org", "http://cran.rstudio.com"))'
    
notifications:
  email:
    on_success: never
    on_failure: never

script: 
  - |
    R CMD build .
    travis_wait 40 R CMD check RSP*tar.gz

r_github_packages: 
  - r-lib/covr

after_success:
  - travis_wait 40 Rscript -e 'covr::codecov()'
