language: R
cache: packages
sudo: required
dist: trusty

r_check_args: --as-cran --run-donttest

r_packages:
    - covr

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - R -e 'install.packages("rgdal", repos="http://R-Forge.R-project.org")'

after_success:
  - Rscript -e 'covr::codecov()'