# Use R language
language: r
cache: packages

repos: 
  CRAN: https://cran.rstudio.com
  rforge: http://R-Forge.R-project.org

before_install:
  - R -e 'install.packages("rgdal", repos=c("http://R-Forge.R-project.org", "http://cran.rstudio.com"))'

#Define R-versions
r:
  - release
  - devel

apt_packages:
  - libv8-dev
  - librsvg2-dev

r_github_packages: 
  # - r-lib/testthat
  - r-lib/covr

# environment variables set for all builds
env:
  global:
  # don't treat missing suggested packages as error
  - _R_CHECK_FORCE_SUGGESTS_=false

after_success:
  - travis_wait 40 Rscript -e 'covr::codecov()'

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      - libgtk2.0-dev

      