# Use R language
language: r
sudo: required
dist: trusty
# cache: packages
cache: 
  - ccache

#Define R-versions
r:
  - release
  - devel
  - oldrel

apt_packages:
  - libv8-dev
  - librsvg2-dev

r_github_packages: 
  # - r-lib/testthat
  - r-lib/covr

# environment variables set for all builds
env:
  global:
  # don't treat missing suggested packages as error
  - _R_CHECK_FORCE_SUGGESTS_=false

after_success:
  - travis_wait 40 Rscript -e 'covr::codecov()'

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libudunits2-dev
      - libgtk2.0-dev
      - devscripts 
      - libgdal-dev
      - libproj-dev
      - libgeos-dev
      - libudunits2-dev
      - libnetcdf-dev
      - netcdf-bin