before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - R -e 'install.packages("rgdal", repos=c("http://R-Forge.R-project.org", "http://cran.rstudio.com"))'      
  
language: r
cache: packages
sudo: required

r_packages:
  - utils
  - stats
  - testthat
  - mapproj
  - maptools
  - deldir
  - PBSmapping
  - RANN
  - colorspace
  - RandomFields
  - shape
  - devtools
  - mixtools
  - sp
  - maps
  - mapdata
  - TMB

warnings_are_errors: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libudunits2-dev
      - libgdal-dev
      - libproj-dev