language: r
r:
  - release
  - devel

sudo: false
cache: packages
script:
  - Rscript -e "rmarkdown::render_site('.')"
  - touch _site/.nojekyll
dist: xenial

warnings_are_errors: false

# before_install:
  
before_script:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then R -e "install.packages('rgdal', type = 'source')"; fi
  - R -e 'install.packages("rgdal", repos="http://R-Forge.R-project.org")'
  - R -q -e 'install.packages("remotes"); remotes::install_github("ropenscilabs/tic"); tic::prepare_all_stages()'

addons:
  apt:
    sources:
      - sourceline: 'ppa:opencpu/jq'
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
      - sourceline: 'deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main'
    packages:
      - libproj-dev
      - libgeos-dev
      - libspatialite-dev
      - libgdal-dev
      - gdal-bin
      - libgdal1-dev
      - libproj-dev