language: r
r: '4.0.2'
sudo: required
cache: packages

os: macOS-latest
# osx_image: xcode12u

disable_homebrew: true
  
latex: false # Disables vignette to speed up build

warnings_are_errors: false

script: 
  - |
    R CMD build .
    travis_wait 50 R CMD check RSP*tar.gz
addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev
      - libproj-dev

before_install:
  - R -e 'install.packages("rgdal", repos=c("http://R-Forge.R-project.org", "http://cran.rstudio.com"))'      
  
r_packages:
  - sp
  - rgdal
  - rgeos
  
r_github_packages: 
  - r-lib/covr

after_success:
  - travis_wait 40 Rscript -e 'covr::codecov()'