before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  
language: r
cache: packages
sudo: required

r_packages:
  - utils
  - stats
  - testthat
  - mapproj
  - maptools
  - deldir
  - PBSmapping
  - RANN
  - colorspace
  - RandomFields
  - shape
  - devtools
  - mixtools
  - sp
  - maps
  - mapdata
  - TMB

r_github_packages:
  - kaskr/TMB_contrib_R/TMBhelper

warnings_are_errors: false
