language: r
sudo: required
cache: packages
warnings_are_errors: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libudunits2-dev
      - libgdal-dev
      - libproj-dev
      
before_install:
  - sudo apt-get update
  - sudo apt-get install libgdal-dev libproj-dev
  - sudo apt install libgeos++dev
  - R -e 'install.packages("rgdal", repos=c("http://R-Forge.R-project.org", "http://cran.rstudio.com"))'      
  - R -e 'install.packages("rgeos", repos=c("http://R-Forge.R-project.org", "http://cran.rstudio.com"))'      