# Use R language
language: r
sudo: required
dist: trusty
cache:
  - packages
  - ccache
services:
  - docker

warnings_are_errors: false

#Define R-versions
r:
  - release
  - devel
  - oldrel

# apt_packages:
#   - libv8-dev
#   - librsvg2-dev

r_github_packages: 
  - r-lib/testthat
  - r-lib/covr

# environment variables set for all builds
env:
  global:
  # don't treat missing suggested packages as error
  - _R_CHECK_FORCE_SUGGESTS_=false

before_script:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then R -e "install.packages('rgdal', type = 'source')"; fi

before_install:
  - "docker pull ubuntu:16.04"
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install libgdal-dev libgeos-dev libproj-dev libudunits2-dev libv8-dev libprotobuf-dev protobuf-compiler libjq-dev
  # - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  # - sudo apt-get --yes --force-yes update -qq
  # - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  # - sudo apt-get install -y gdal-bin
  # - R -e 'install.packages("GDAL", repos=c("http://R-Forge.R-project.org", "http://cran.rstudio.com"))'
  # - R -e 'install.packages("PROJ", repos=c("http://R-Forge.R-project.org", "http://cran.rstudio.com"))'
  # - R -e 'install.packages("rgdal", repos=c("http://R-Forge.R-project.org", "http://cran.rstudio.com"))'

after_success:
  - travis_wait 40 Rscript -e 'covr::codecov()'

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - devscripts 
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      - libgtk2.0-dev

