language: r
sudo: required
cache: packages

os:
  - macos
  # - windows # not suported yet!

env:
  - TEST_SUITE=units
  - TEST_SUITE=integration

warnings_are_errors: false

script:
  - "bundle exec rake test:$TEST_SUITE" 
  - |
    R CMD build .
    travis_wait 50 R CMD check RSP*tar.gz
addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev
      - libproj-dev

before_install:
  - R -e 'install.packages("rgdal", repos=c("http://R-Forge.R-project.org", "http://cran.rstudio.com"))'      
  
r_packages:
  - sp
  - rgdal
  - rgeos

r_github_packages: 
  - r-lib/covr

after_success:
  - travis_wait 40 Rscript -e 'covr::codecov()'
